[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan config:cache && php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT"

[env]
APP_ENV = "production"
APP_DEBUG = "false"
